### ISSUE TITLE
고생하셨습니다!

### ISSUE THREAD

**Issue by Gwonyeong** [dailythm/dailythm-sumin#1]
분수의 덧셈 푸는 모습 잘 봤습니다.

**Comment by sumin-dev** [comment]
> 분수의 덧셈 푸는 모습 잘 봤습니다.

감사합니다,,,두시간정도 걸렸습니다,,,반복문 안에 조건문 안에 반복문 안에 조건문을 사용한 저의 문제였습니다,,,수민아 정신차려라(⓿_⓿)
