### ISSUE TITLE
외계 행성의 나이

### ISSUE THREAD

**Issue by Gwonyeong** [dailythm/dailythm-sumin#2]
https://github.com/dailythm/dailythm-sumin/blob/main/%EC%9E%85%EB%AC%B8/221103.md#%EC%99%B8%EA%B3%84%ED%96%89%EC%84%B1%EC%9D%98-%EB%82%98%EC%9D%B4

인상깊은 코드였습니다! 

다만 조금 더 넓은 범위로 나아가면( 숫자가 두 자리 수가 된다거나)  활용하기 어려울 수 있을 것 같습니다.

@sumin-dev 님께 혹시나 좋은 정보가 되실까 해서 정보 몇 개 남깁니다.

아스키 코드는 문자를 숫자로, 숫자를 문자로 바꾸는 문제 등에서 유용하게 사용할 수 있습니다. 

아스키 코드는 대문자와 소문자로 나눈 알파벳 및 여러 문자를 표를 제작해 숫자로 표현해 놓은 것입니다. 

[파이썬 아스키 코드](https://lsjsj92.tistory.com/201)

문자를 아스키 코드로 바꾸는 내장함수, 아스키 코드를 해당 문자로 바꿔주는  내장함수,

대문자 A는 65, 소문자 a는 97번 이라는 것 정도는 알고계시면 알고리즘 문제를 풀 때 큰 도움이 되실겁니다!

아래는 아스키 코드를 이용해 제가 작성한 코드입니다.

https://github.com/dailythm/dailythm-GwonYeong/blob/main/2022/Nov/02(Wed)/2.%20%EC%99%B8%EA%B3%84%ED%96%89%EC%84%B1%EC%9D%98%20%EB%82%98%EC%9D%B4.py

**Comment by sumin-dev** [comment]
@kwanyung 정말 감사합니다~! 저 코드를 구현할 때 제한조건이 1000까지여서 하드코딩으로 시도하였지만 비효율적이라는 생각을 하고 있었습니다😥 다른 사람의 풀이와 권영님 코드도 봤는데 97을 더하는 이유를 몰라서 활용을 못했습니다! 아스키 코드였군요 덕분에 큰 도움이 되었습니다. 답안 코드에도 참고자료로 링크 걸어둬야겠어요! 고맙습니다(❁´◡`❁)
